### ISSUE TITLE
Getting "Error: Cannot find module 'tslib'" while using this package in cjs

### ISSUE THREAD

**Issue by bhargavprajapatiFynd** [udamir/api-smart-diff#4]
<img width="1069" alt="Screenshot 2023-07-24 at 12 55 23 PM" src="https://github.com/udamir/api-smart-diff/assets/117252424/7c57ee96-e214-4847-92d9-3f17f01ab9d8">

**Comment by udamir** [comment]
fixed in api-smart-diff@0.6.11

**Comment by bhargavprajapatiFynd** [comment]
Its working now, Thanks @udamir
